### ISSUE TITLE
[2023年03月02日]: 医生正在书写病例 ，病人去交费不能同时进行 交不了费用

### ISSUE THREAD

**Issue by Lidong44921** [smallprogram/CgyyIssue#18]
### 反馈科室

医生正在书写病例 ，病人去交费不能同时进行 交不了费用

### 描述您遇到的问题

医生正在书写病例 ，病人去交费不能同时进行 交不了费用

### 那个医疗系统相关信息

His

**Comment by superwangCC** [comment]
综合查询-门诊病历查询-病历修改菜单
