### ISSUE TITLE
[2023年3月2日]: 体检系统接口问题

### ISSUE THREAD

**Issue by LiuXingSir** [smallprogram/CgyyIssue#21]
### 反馈科室

体检科

### 描述您遇到的问题

- [x] 体检免费患者，不收费的，LIS与PACS如何提取患者信息并正常执行检查检验业务。
- [x] 体检患者包含部分免费检查检验项目的患者，LIS与PACS如何提取患者信息并正常执行检查检验业务。
- [x] 体检系统不同费用的套餐没有，体检操作员只能去单个项目中改折扣价格，操作十分繁琐，工作效率低下。
- [x] 体检打印的条码LIS系统无法区分项目

### 那个医疗系统相关信息

HIS
LIS
PACS

**Comment by superwangCC** [comment]
接口已经完善 需要体检系统配合

**Comment by smallprogram** [comment]
#31

**Comment by smallprogram** [comment]
已解决
