### ISSUE TITLE
[2023年3月3日]: 候诊患者明细列表中缺少患者挂号次序号、已挂号多少人、待接诊多少人。已接诊患者列表中缺少每个患者接诊时间

### ISSUE THREAD

**Issue by LiuXingSir** [smallprogram/CgyyIssue#24]
### 反馈科室

无

### 描述您遇到的问题

候诊患者明细列表中缺少患者挂号次序号、已挂号多少人、待接诊多少人。已接诊患者列表中缺少每个患者接诊时间

### 那个医疗系统相关信息

HIS

**Comment by superwangCC** [comment]
已增加候诊病人数量显示及明细

**Comment by smallprogram** [comment]
> 已增加候诊病人数量显示及明细，主界面右小角

已接诊患者列表中缺少每个患者接诊时间

**Comment by superwangCC** [comment]
已诊里边 就诊时间 就是接诊时间，代表医生哪会开始就诊的 这个不对吗？

**Comment by smallprogram** [comment]
> 已诊里边 就诊时间 就是接诊时间，代表医生哪会开始就诊的 这个不对吗？

对
