### ISSUE TITLE
[2023年3月3日]: 每日科室各种费用汇总查询不到，例如（药费、手术费、麻醉费等汇总）

### ISSUE THREAD

**Issue by LiuXingSir** [smallprogram/CgyyIssue#27]
### 反馈科室

无

### 描述您遇到的问题

每日科室各种费用汇总查询不到，例如（药费、手术费、麻醉费等汇总）

### 那个医疗系统相关信息

HIS

**Comment by superwangCC** [comment]
![image](https://user-images.githubusercontent.com/113157820/222952949-2ce654b1-7ca3-45b6-abd1-558fb7deb182.png)
住院医生已经加入
