### ISSUE TITLE
[2023年3月3日]: 针刀软组织松解术中，性别、年龄、科室无法写入

### ISSUE THREAD

**Issue by LiuXingSir** [smallprogram/CgyyIssue#30]
### 反馈科室

无

### 描述您遇到的问题

针刀软组织松解术中，性别、年龄、科室无法写入

### 截图

![dee3beca95d8d9063f455685c860538](https://user-images.githubusercontent.com/108500926/222608042-8e05ae46-465e-49a4-a810-0a22386c1ffc.jpg)

### 那个医疗系统相关信息

HIS

**Comment by superwangCC** [comment]
已调整
